# Generated by Django 5.2.6 on 2025-12-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_country_initiative_delete_proof_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="thoughts",
            field=models.CharField(
                blank=True,
                help_text="One word opinion about the country",
                max_length=50,
            ),
        ),
    ]
