# Generated by Django 5.2.6 on 2025-12-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_hobby_description_hobby_reason_hobby_social_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hobby",
            name="project",
        ),
        migrations.RemoveField(
            model_name="hobby",
            name="time_per_week",
        ),
        migrations.RemoveField(
            model_name="hobby",
            name="value",
        ),
        migrations.AlterField(
            model_name="hobby",
            name="reason",
            field=models.CharField(
                blank=True, help_text="Why this hobby is important", max_length=200
            ),
        ),
    ]
