# Generated by Django 5.2.6 on 2025-12-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_hobby_project_remove_hobby_time_per_week_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="SpokenLanguage",
        ),
        migrations.RemoveField(
            model_name="project",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="project",
            name="github_link",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_link",
        ),
        migrations.RemoveField(
            model_name="project",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="technologies",
        ),
        migrations.RemoveField(
            model_name="skills",
            name="icon",
        ),
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(
                help_text="Select or create skills used in this project (required)",
                related_name="projects",
                to="api.skills",
            ),
        ),
        migrations.AlterField(
            model_name="skills",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Programming Languages", "Programming Languages"),
                    ("Packages", "Packages"),
                    ("Soft", "Soft"),
                    ("Hard", "Hard"),
                    ("Spoken Languages", "Spoken Languages"),
                ],
                help_text="Select the category for this skill",
                max_length=50,
            ),
        ),
    ]
