# Generated by Django 5.2.6 on 2025-12-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_photo_alter_book_options_remove_book_isbn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="project",
        ),
    ]
