# Generated by Django 5.2.6 on 2025-12-27 09:02

from django.db import migrations, models


def delete_records_without_images(apps, schema_editor):
    """Delete any existing records that don't have images"""
    Project = apps.get_model('api', 'Project')
    Book = apps.get_model('api', 'Book')
    Photo = apps.get_model('api', 'Photo')
    
    # Delete projects without images
    projects_deleted = Project.objects.filter(image__isnull=True).count()
    Project.objects.filter(image__isnull=True).delete()
    if projects_deleted > 0:
        print(f"Deleted {projects_deleted} project(s) without images")
    
    # Delete books without cover images
    books_deleted = Book.objects.filter(cover_image__isnull=True).count()
    Book.objects.filter(cover_image__isnull=True).delete()
    if books_deleted > 0:
        print(f"Deleted {books_deleted} book(s) without cover images")
    
    # Delete photos without images
    photos_deleted = Photo.objects.filter(image__isnull=True).count()
    Photo.objects.filter(image__isnull=True).delete()
    if photos_deleted > 0:
        print(f"Deleted {photos_deleted} photo(s) without images")


def reverse_delete_records(apps, schema_editor):
    """Reverse operation - nothing to do as records are already deleted"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_book_project"),
    ]

    operations = [
        # First, delete any records without images
        migrations.RunPython(
            delete_records_without_images,
            reverse_delete_records,
        ),
        # Then make the image fields required
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(help_text='Book cover image (required)', upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Photo image (required)', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='Project image (required)', upload_to='projects/'),
        ),
    ]
