# Generated by Django 5.2.6 on 2025-12-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_make_images_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="skills",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Icon/image for this skill",
                null=True,
                upload_to="skills/icons/",
            ),
        ),
    ]
