# Generated by Django 5.2.6 on 2025-12-27 09:19

from django.db import migrations


def move_packages_to_programming_languages(apps, schema_editor):
    """Move skills with Packages category to Programming Languages"""
    Skills = apps.get_model('api', 'Skills')
    
    # Move all Packages skills to Programming Languages
    packages_skills = Skills.objects.filter(category='Packages')
    count = packages_skills.count()
    packages_skills.update(category='Programming Languages')
    
    if count > 0:
        print(f"Moved {count} skill(s) from 'Packages' to 'Programming Languages'")


def reverse_move(apps, schema_editor):
    """Reverse operation - move back to Packages (if needed)"""
    # This is a one-way migration, but we'll keep the reverse for completeness
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_add_skill_icon"),
    ]

    operations = [
        # First, move existing Packages skills to Programming Languages
        migrations.RunPython(
            move_packages_to_programming_languages,
            reverse_move,
        ),
        # Note: Removing 'Packages' from CATEGORY_CHOICES is handled in the model change
        # Existing data with 'Packages' category will be moved to 'Programming Languages'
    ]
