# Generated by Django 5.2.6 on 2025-12-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_packages_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="skills",
            name="description",
        ),
        migrations.AlterField(
            model_name="skills",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Programming Languages", "Programming Languages"),
                    ("Soft", "Soft"),
                    ("Hard", "Hard"),
                    ("Spoken Languages", "Spoken Languages"),
                ],
                help_text="Select the category for this skill",
                max_length=50,
            ),
        ),
    ]
