"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', "django-insecure-!1^b)wdp*5uh%#wr!h-w9_p*wcap8ze4$6hw6$pex-mn*53u8w")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Allow Vercel domains and custom domains
# IMPORTANT: Optionally set ALLOWED_HOSTS environment variable in Vercel with your custom domain
# Example: ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com
# If not set, the VercelCustomDomainMiddleware will handle custom domains automatically
custom_hosts = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', '').split(',') if host.strip()]

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.vercel.app',
    'heal.industries',
    'www.heal.industries',
] + custom_hosts

# Use X-Forwarded-Host header (Vercel sets this for custom domains)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "cloudinary_storage",  # Must be before 'django.contrib.staticfiles' for media files
    "api",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add WhiteNoise for static files (must be after SecurityMiddleware)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Add custom domain middleware for Vercel if in production
if os.environ.get('VERCEL'):
    # Insert after SecurityMiddleware to bypass ALLOWED_HOSTS check
    MIDDLEWARE.insert(2, "api.middleware.VercelCustomDomainMiddleware")

# WhiteNoise configuration - allow serving from STATICFILES_DIRS
# This enables WhiteNoise to serve files even if collectstatic hasn't run
try:
    import whitenoise
    # Configure WhiteNoise to add files from STATICFILES_DIRS to its list
    # This allows serving files directly from source directories
    WHITENOISE_USE_FINDERS = True  # Enable finding files in STATICFILES_DIRS
except ImportError:
    pass

ROOT_URLCONF = "portfolio.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.parent / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "portfolio.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL if database environment variables are set
# On Vercel, we MUST use PostgreSQL (SQLite doesn't work on serverless)
if os.environ.get('DB_NAME'):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME"),
            "USER": os.environ.get("DB_USER"),
            "PASSWORD": os.environ.get("DB_PASSWORD"),
            "HOST": os.environ.get("DB_HOST"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
elif os.environ.get('VERCEL'):
    # On Vercel without DB config, try to use PostgreSQL with connection pooling
    # If DB env vars are missing, provide a helpful error message
    db_name = os.environ.get('DB_NAME')
    if not db_name:
        # Log warning but don't crash - allow app to start
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(
            "VERCEL environment detected but DB_NAME not set. "
            "Please configure Neon database environment variables in Vercel."
        )
    
    # Try to use PostgreSQL if credentials are available
    if db_name:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": os.environ.get("DB_NAME"),
                "USER": os.environ.get("DB_USER"),
                "PASSWORD": os.environ.get("DB_PASSWORD"),
                "HOST": os.environ.get("DB_HOST"),
                "PORT": os.environ.get("DB_PORT", "5432"),
                "OPTIONS": {
                    "connect_timeout": 10,
                    "sslmode": "require",
                },
            }
        }
    else:
        # Fallback to in-memory SQLite (read-only, allows app to start)
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": ":memory:",
            }
        }
else:
    # SQLite for local development only
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR.parent / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR.parent / "static",
]

# WhiteNoise configuration for serving static files on Vercel
# Use CompressedStaticFilesStorage (without manifest) for easier debugging
# Manifest storage can cause issues if files aren't found
# WhiteNoise will serve from STATICFILES_DIRS if collectstatic hasn't run
try:
    import whitenoise
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
except ImportError:
    pass  # WhiteNoise not installed, use default storage

# Media files (User uploaded content)
# Use Cloudinary for production (Vercel), local storage for development
if os.environ.get('VERCEL') or os.environ.get('CLOUDINARY_CLOUD_NAME'):
    # Cloudinary configuration for production
    try:
        import cloudinary
        import cloudinary.uploader
        import cloudinary.api
        
        CLOUDINARY_STORAGE = {
            'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
            'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
            'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
        }
        
        # Use Cloudinary for media files
        DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
        
        # Cloudinary settings (only if credentials are provided)
        if CLOUDINARY_STORAGE['CLOUD_NAME']:
            cloudinary.config(
                cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
                api_key=CLOUDINARY_STORAGE['API_KEY'],
                api_secret=CLOUDINARY_STORAGE['API_SECRET'],
            )
        
        MEDIA_URL = '/media/'  # Cloudinary will handle the actual URL
    except ImportError:
        # Cloudinary not installed, fall back to local storage
        MEDIA_URL = "media/"
        MEDIA_ROOT = BASE_DIR / "media"
else:
    # Local storage for development
    MEDIA_URL = "media/"
    MEDIA_ROOT = BASE_DIR / "media"

# File upload size limits (for Vercel compatibility)
# Vercel has a 4.5MB limit for serverless functions, but we allow up to 10MB for images
# Note: Large files should use cloud storage in production
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# CORS settings - Configure for React frontend and custom domains
# Allow all origins in production (Vercel) to support custom domains
if os.environ.get('VERCEL'):
    # In production, allow all origins (custom domains will work)
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # In development, restrict to localhost
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# GitHub API Configuration
GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN', '')
GITHUB_USERNAME = os.environ.get('GITHUB_USERNAME', 'ElSancturioDeThomas')

# Caching for GitHub contributions
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
