# Generated by Django 5.2.6 on 2025-12-24 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="ISO country code (e.g., US, AU)",
                        max_length=2,
                    ),
                ),
                (
                    "flag_emoji",
                    models.CharField(
                        blank=True, help_text="Flag emoji or icon", max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="initiatives/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiatives",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Proof",
        ),
        migrations.RemoveField(
            model_name="skillsdeveloped",
            name="project",
        ),
        migrations.DeleteModel(
            name="Travel",
        ),
        migrations.AlterModelOptions(
            name="skills",
            options={
                "ordering": ["skill_type", "category", "-proficiency_level", "name"],
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="hobby",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hobbies",
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="skills",
            name="programming_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skills",
                to="api.programminglanguage",
            ),
        ),
        migrations.AddField(
            model_name="skills",
            name="skill_type",
            field=models.CharField(
                choices=[
                    ("programming", "Programming Language"),
                    ("spoken", "Spoken Language"),
                    ("business", "Business Skill"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="skills",
            name="spoken_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skills",
                to="api.spokenlanguage",
            ),
        ),
        migrations.DeleteModel(
            name="SkillsDeveloped",
        ),
    ]
