# Generated by Django 5.2.6 on 2025-12-25 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_country_thoughts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skills",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.RemoveField(
            model_name="skills",
            name="proficiency_level",
        ),
        migrations.RemoveField(
            model_name="skills",
            name="programming_language",
        ),
        migrations.RemoveField(
            model_name="skills",
            name="skill_type",
        ),
        migrations.RemoveField(
            model_name="skills",
            name="spoken_language",
        ),
    ]
