# Generated by Django 5.2.6 on 2025-12-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_skills_options_remove_skills_proficiency_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="initiative",
            name="project",
        ),
        migrations.DeleteModel(
            name="ProgrammingLanguage",
        ),
        migrations.DeleteModel(
            name="Initiative",
        ),
    ]
