# Generated by Django 5.2.6 on 2025-12-25 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_initiative_project_delete_programminglanguage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hobby",
            name="description",
        ),
        migrations.AddField(
            model_name="hobby",
            name="reason",
            field=models.TextField(blank=True, help_text="Why this hobby is important"),
        ),
        migrations.AddField(
            model_name="hobby",
            name="social",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("maybe", "Maybe")],
                default="maybe",
                help_text="Is this a social activity?",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="hobby",
            name="time_per_week",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Hours per week spent on this hobby",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hobby",
            name="value",
            field=models.IntegerField(
                default=3,
                help_text="Likert scale value from 1-5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
